import { Sidebar } from '@/layouts';
import type { Metadata } from 'next';
import './globals.css';
import dynamic from 'next/dynamic';

const Modal = dynamic(() => import('@/layouts/Modal'));

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Sidebar />
                <main className="ml-sidebar">{children}</main>
                <Modal />
            </body>
        </html>
    );
}
