import { LayoutTheme, Sidebar } from '@/layouts';
import type { Metadata } from 'next';
import './globals.css';
import './components.css';
import dynamic from 'next/dynamic';

const Modals = dynamic(() => import('@/layouts/Modals'));

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    modal,
}: {
    children: React.ReactNode;
    modal: React.ReactNode;
}) {
    return (
        <html lang="en">
            <LayoutTheme>
                <Sidebar />
                <main className="ml-sidebar">{children}</main>
                <Modals />
                {modal}
            </LayoutTheme>
        </html>
    );
}
