import { LayoutTheme, Sidebar } from '@/layouts';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import dynamic from 'next/dynamic';
import { notFound } from 'next/navigation';
import './components.css';
import './globals.css';

const Modals = dynamic(() => import('@/layouts/Modals'));

interface RootLayoutProps {
    children: React.ReactNode;
    modal: React.ReactNode;
    params: { locale: string };
}

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const locales = ['en', 'vi', 'zh'];

const loadMessages = async (locale: string) => {
    const url = `https://api.i18nexus.com/project_resources/translations/${locale}.json?api_key=${process.env.I18NEXUS_API_KEY}`;

    const res = await fetch(url, {
        next: { revalidate: false },
    });

    return res.json();
};

export default async function RootLayout({ children, modal, params: { locale } }: RootLayoutProps) {
    let messages;
    // Validate that the incoming `locale` parameter is valid
    const isValidLocale = locales.some(cur => cur === locale);
    if (!isValidLocale) notFound();

    try {
        messages = await loadMessages(locale);
    } catch (error) {
        notFound();
    }

    return (
        <html lang={locale}>
            <NextIntlClientProvider locale={locale} messages={messages.default}>
                <LayoutTheme>
                    <Sidebar />
                    <main className="ml-sidebar">{children}</main>
                    <Modals />
                    {modal}
                </LayoutTheme>
            </NextIntlClientProvider>
        </html>
    );
}
